# Generated by Django 5.1.4 on 2025-01-09 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outflow', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outflow',
            old_name='ccreated_at',
            new_name='created_at',
        ),
    ]
